name: $(date:yyMMdd)$(rev:r) $(Build.SourceBranch)

trigger:
- master

pool:
  name: Default

steps:
- task: CmdLine@2
  inputs:
    script: |
      lines=`git branch -r --merged  | egrep -v "(^\*|master|main|dev|release|pull)" | sed 's/origin\///' | wc -l`
      git branch -r --merged  | egrep -v "(^\*|master|main|dev|release|pull)" | sed 's/origin\///'
      
      if [ "$lines" -gt "5" ]; then 
        echo "###########################################################################################"
        echo "  More than 5 branches already merged"
        echo "###########################################################################################"
        exit 1; 
      fi
  displayName: 'Merged Branches in $(Build.SourceBranch)'

- task: CmdLine@2
  inputs:
    script: |
      lines=`git branch -r | egrep -v "(^\*|master$|main$|develop$|release$|releases/|bugfix/|hotfix/|maintenance/|pull/|feature/)" | sed 's/origin\///' | wc -l`
      git branch -r | egrep -v "(^\*|master$|main$|develop$|release$|releases/|bugfix/|hotfix/|maintenance/|pull/|feature/)" | sed 's/origin\///'
      
      if [ "$lines" -gt "1" ]; then 
        echo "###########################################################################################"
        echo "  Incorrect Branch Names"
        echo "###########################################################################################"
        exit 1; 
      fi
  displayName: 'Bad Branch Names'
